export * from '~/queries/root'
export * from '~/queries/posts'
export * from '~/queries/news'
export * from '~/queries/notices'
export * from '~/queries/promotion'
export * from '~/queries/main'
export * from '~/queries/services'
