export * from '~/queries/services/homepage'
export * from '~/queries/services/singlepage'
export * from '~/queries/services/publishing'
export * from '~/queries/services/appdesign'
export * from '~/queries/services/branding'
export * from '~/queries/services/plan'
